---
- name: Install packages
  tasks:
    - name: install webserver
      yum:
        name: httpd
        state: latest
    - name: restart service
      service:
        name: httpd
        state: reloaded
        enabled: yes
        